return {
	-- "ThePrimeagen/refactoring.nvim",
	-- dependencies = {
	-- 	"nvim-lua/plenary.nvim",
	-- 	"nvim-treesitter/nvim-treesitter",
	-- },
	-- config = function()
	-- 	require("refactoring").setup()
	--
	-- 	vim.keymap.set("x", "<leader>ref", function()
	-- 		require("refactoring").refactor("Extract Function")
	-- 	end, { desc = "[e]xtract Function" })
	-- 	-- vim.keymap.set("x", "<leader>reF", function()
	-- 	-- 	require("refactoring").refactor("Extract Function To File")
	-- 	-- end, { desc = "[E]xtract Function To File" })
	--
	-- 	vim.keymap.set("x", "<leader>rev", function()
	-- 		require("refactoring").refactor("Extract Variable")
	-- 	end, { desc = "Extract Variable" })
	--
	-- 	-- Extract variable supports only visual mode
	-- 	vim.keymap.set("n", "<leader>rif", function()
	-- 		require("refactoring").refactor("Inline Function")
	-- 	end, { desc = "[i]nline [f]unction" })
	--
	-- 	-- Inline func supports only normal
	-- 	vim.keymap.set({ "n", "x" }, "<leader>riv", function()
	-- 		require("refactoring").refactor("Inline Variable")
	-- 	end, { desc = "[i]nline [v]ariable" })
	-- 	-- Inline var supports both normal and visual mode
	--
	-- 	vim.keymap.set("n", "<leader>reb", function()
	-- 		require("refactoring").refactor("Extract Block")
	-- 	end, { desc = "[e]xtract [b]lock" })
	-- 	-- vim.keymap.set("n", "<leader>rbf", function()
	-- 	-- 	require("refactoring").refactor("Extract Block To File")
	-- 	-- end, { desc = "Extract Block To File" })
	-- 	-- Extract block supports only normal mode
	-- end,
}
