-- vim.api.nvim_create_autocmd('BufWritePre', {
--   pattern = '*',
--   callback = function(args)
--     vim.lsp.buf.format()
--   end,
-- })

-- vim.api.nvim_create_autocmd('BufWritePost', {
--   pattern = { '*' },
--   callback = function(args)
--     require('conform').format { bufnr = args.buf }
--     vim.lsp.buf.format()
--   end,
-- })

-- vim.api.nvim_create_autocmd('BufWritePost', {
--   pattern = { '*' },
--   callback = function(args)
--     require('conform').format { bufnr = args.buf }
--     -- vim.lsp.buf.format()
--   end,
-- })

-- vim.api.nvim_create_autocmd({ 'BufWritePre' }, {
--   pattern = { '*.tf', '*.tfvars' },
--   callback = function()
--     vim.lsp.buf.format()
--   end,
-- })
--
-- require('lspconfig').terraformls.setup {}
